
services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      LANG: C.UTF-8
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
  
  backend:
    build: ./backend
    working_dir: /backend
    volumes:
      - .:/backend
    ports:
      - "8000:8000"
    depends_on:
      - db
    command: >
      sh -c "
        until nc -z db 3306; do
          sleep 1;
        done;
        sh backend/setup.sh 
      "
    environment:
      DJANGO_SUPERUSER_USERNAME: root
      DJANGO_SUPERUSER_EMAIL: root@example.com
      DJANGO_SUPERUSER_PASSWORD: root

  frontend:
    build: ./frontend
    working_dir: /frontend/frontend/app
    volumes:
      - .:/frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    command: > 
      sh -c "
      until nc -z backend 8000; do
        sleep 1;
      done;
      npm start
      "

volumes:
  db_data: